
## 具体介绍

线性混合效应模型（linear mixed-effects models，LMM；又称 hierarchical models 或 multilevel models），简称混合模型 [@baayen2008]，是一般线性回归模型的一种扩展模型，它通过随机效应参数捕捉观测数据之间的依赖性，比如每个被试间观测数据的依赖性。与忽略这些依赖关系的传统分析相比，混合模型可以提供更准确的效应估计，以及更高的统计检验力 [@tuerlinckx2006]。
在解释混合模型结果时，往往会提及两个特有的统计概念，即固定效应与随机效应（fixed and random effects）。其中，固定效应代表特定模型项（即主效应或交互作用）或参数在总体或群体层面对因变量的平均效应。固定效应通常是研究者感兴趣的实验操作变量，它的统计学意义的与方差分析或回归模型中对给定项的统计检验的结果基本相同，即固定效应可以用来检验因素水平之间的差异性假设。相比之下，随机效应解释的是数据中来自不同来源随机变量的变异，比如不同被试与不同实验刺激带来的变异，而这些效应往往是研究者不感兴趣以及想要控制的变异。
需要注意的是，这些随机变量的来源必须是分组变量，即称名变量，如实验条件、实验刺激或被试，而连续变量不能作为随机效应。在真实实验中，随机效应的意义在于，当研究者希望了解某个实验因子是否对所有被试具有普遍影响时，即实验因子的效应不会受到被试差异影响，通过在模型中指定随机效应，研究者可以排除被试差异带来的特异性，从而获得一个更普遍的对固定效应更精确的估计。

为了让读者更好的理解固定效应与随机效应的概念，以及混合效应模型与方差分析的关系，我们将从最基本的回归模型与方差分析的数学原理开始介绍，以便读者更好的理解为何混合效应模型可以解决传统分析方法无法解决的问题。
$$
Y_{i}=\beta_{0} + \beta_{\delta}X_{i} + \epsilon_{i}
$$   {#eq:eq1}

首先，一般线性回归模型的表达式如 @eq:eq1。其中，$Y_{i}$ 是因变量，代表观测变量，$i$ 为第 $1$ 到 $i$ 个观测点。$X_{i}$ 是自变量，代表了感兴趣的操作变量，比如，任务难度或者学生成智力。参数 $\beta_{0}$ 是回归截距项，一般代表随机变量$Y$的总体平均值；参数$\beta_{\delta}$ 为回归斜率项，代表研究因子效应的大小。$\epsilon_{i}$ 为残差，代表模型不能解释的部分变异。
需要注意的是，使用一般线性模型需要满足残差服从独立同分布的前提假设，即每一个观测值的残差是相互独立的，并且在总体上所有观测值的残差应该遵循正态分布。对于现实中收集的数据，比如包含重复测量的实验数据，单个被试内的数据具有相互依存性，因此独立性的前提假设难以满足。


当任务难度为组间设计时，每个观测数据点为各被试的平均反应时，此时一般线性模型的前提假设更容易满足，因此可以通过一般线性模型来检验不同任务难度对于反应时的影响。然而，当任务难度为组内设计时，每个被试会在不同任务难度条件下产生两个不同的观测数据点，即存在重复测量，此时一般线性模型的前提假设难以满足，只能使用配对 t 检验或者重复测量方差分析对数据进行检验。
实际上，配对t检验或者重复测量方差分析只是额外的考虑了不同被试带来的变异，但并没有考虑每个被试内试次间相互影响变异，即对每个被试在不同任务难度下的反应时求平均值依然不能完全考虑各被试中不同试次的依赖程度。
为了解决这个问题，混合效应模型将任务难度作为固定效应，将被试随机效应，并且考虑了各被试中不同试次的变异，即使用混合效应模型时不需要将观测数据在被试或者实验条件层面进行平均或汇总。

当混合效应模型只考虑固定效应时，其表达式与一般线性模型类似，其表达式如下公式 @eq:eq2：
$$ 
\begin{aligned}
Y_{i,j,k} &=\beta_{0}+\beta_{\delta} X_{i,k}+\epsilon_{i,j,k}
\end{aligned} 
$$  {#eq:eq2}

其中，$Y_{i,j,k}$ 为观测变量，比如反应时，$i$ 为被试编号，$j$ 为试次编号，$k$ 为实验条件，比如任务难度，简单条件编码为-1，困难条件编码为1。$\beta_{0}$ 与 $\beta_{\delta}$ 为固定效应，$\beta_{0}$ 反应了所有试次的平均反应时， $\beta_{\delta}$ 反应了任务难度对于反应时的效应，即两个条件下所有被试反应时的差异。$\epsilon_{i,j,k}$ 为模型残差。
此时，由于模型没有加入随机效应，因此无法解释反应时的个体差异，以及固定效应在不同被试间的一致性。

为了解释反应时的个体差异，可以在混合模型中加入随机截距，其表达式如下 @eq:eq3：
$$
\begin{aligned}
Y_{i,j,k} &=\beta_{0,i,k}+\beta_{\delta} X_{i,k} + \epsilon_{i,j,k} \\
\beta_{0,i,k} &= \beta_{0} + \beta_{i,k}
\end{aligned} 
$$  {#eq:eq3}

与 @eq:eq2 相比，显而易见的是随机截距就是指影响截距项 $\beta_{0,i,k}$ 的随机效应。其中，$\beta_{0}$ 不再是所有试次反应时的均值，而是所有被试平均反应时的均值。而 $\beta_{0,i,k}$ 代表了每个被试的平均反应时（并不一定等于每个被试的平均反应时），即等于被试平均反应时的均值 $\beta_{0}$ 加上个体偏移量 $\beta_{i,k}$。
因此，加入随机截距的混合效应模型可以解释不同被试 $i$ 在反应时上的个体差异 $\beta_{i,k}$ ，这已经足以解释各数据点之间的相关性，比如有些被试的反应更慢，而有些反应更快。
然而，该模型依然无法解释固定效应在不同被试间的一致性。很容易想象，任务难度对反应时的影响对不同被试是不同的，比如某些被试在两种任务难度上的反应都很快，这就导致任务难度的固定效应在这些被试上是小于另一部分被试的。

为了解释固定效应在被试间的一致性，进一步在混合模型中加入随机斜率，其表达式如下 @eq:eq4：
$$
\begin{aligned}
Y_{i,j,k} &=\beta_{0,i,k}+\beta_{\delta,i,k} X_{i,k} + \epsilon_{i,j,k} \\
\beta_{\delta,i,k} &= \beta_{\delta} + \gamma_{i,k}
\end{aligned} 
$$  {#eq:eq4}

与 @eq:eq3 相比，随机斜率指影响斜率项 $\beta_{\delta,i,k}$ 的随机效应。其中，$\beta_{\delta}$ 指固定效应在所有被试上的平均值。而 $\beta_{\delta,i,k}$ 指每个被试独特的固定效应，即等于被固定效应在所有被试上的平均值 $\beta_{\delta}$ 加上个体偏移量 $\gamma_{i,k}$，使用 $\gamma_{i,k}$ 作为固定效应的个体偏移量是为了避免与因变量均值的个体偏移量 $\beta_{i,k}$ 混淆。
此外，随机效应之间可能存在相关性，即随机截距 $\beta_{i,k}$ 与随机斜率 $\gamma_{i,k}$ 服从均值为零的多元正态分布。因此，在建立混合模型前需要假设是否存在随机效应间的相关性，一般混合模型建立时会默认存在随机效应间的相关性。

至此，我们讨论了如何在混合模型中加入不同的随机效应以及他们的相关性来解释被试之间的异质性以及观测数据中的依赖性。需要注意的是，研究者常关心的效应（主效应与交互效应）往往可以与模型的固定效应相对应，并且固定效应的解释不会因为加入随机效应而变化，此外，加入随机效应还能增加对于固定效应估计的准确性。

在确定混合效应模型时，通常需要考虑包含最复杂的随机效应结构 [@barr2013]，即及考虑所有潜在存在的随机截距与随机斜率。然而，此时的模型可能会遭遇不收敛或给出异常估计的问题 [@bates2015]。
相比之下，这种包含复杂随机效应结构的模型通常可以在贝叶斯框架中得到更好的拟合 [@sorensen2016]  [@eager2017]。除此之外，使用贝叶斯方法进行模型拟合还包含其他优势，比如对于参数估计、假设检验、以及结合先验经验的优势，这在前文都有讨论。因此，我们接下来讲介绍如何使用贝叶斯方法来拟合混合模型。

基于贝叶斯框架的模型拟合的特点在于，不同于频率主义框架中将模型参数与实验效应视作固定真值，即当抽样次数接近无穷大时两个样本之间的差距等同于两个总体真实存在的差异，贝叶斯框架将模型参数与实验效应视作存在不确定性的概率事件，即两个总体间的差异不是固定值，而是存在不确信噪音的概率分布。
用贝叶斯公式表示如下 @eq:eq5：
$$
p(\theta|Y) = \frac{p(Y|\theta)*p(\theta)  }{p(Y) }
$$   {#eq:eq5}

公式右部 $p(\theta|Y)$ 为后验概率分布，代表在得到实验数据 $Y$ 的条件下，实验效应为 $\theta$ 的概率。
后验分布可以通过公式左边部分计算，其中$p(\theta)$为先验概率，代表了在未获得实验数据时对实验效应的假设，即可以通过以前的研究实验效应设定该实验的先验效应；$p(Y|\theta)$为似然，代表了在实验效应已知的条件下实验数据出现的概率，可以理解为在混合效应模型已知的条件下，通过该模型预测或生成不同模拟数据的概率；$p(Y)$为边际似然，代表了数据随机抽出的概率，不同于似然是在两个已知差异的总体中进行采样，边际似然则是在所有总体的组合中进行样本的采样，因此可以表示为在所有不同实验效应$\theta$下似然的和，即$p(Y) = \sum_{\theta} p(Y|\theta)*p(theta)$，当$\theta$为连续变量时，$p(Y) = \int_{\theta} p(Y|\theta)*p(theta)d \theta$，更多详情请参考 [@kruschke2018a]。
贝叶斯公式的意义在于说明，参数（实验效应），数据和模型的关系，即如何在结合先验知识和数据的情况下推测模型的参数值。然而，将精力过多的投入到贝叶斯方法本身并不会增强我们对建立模型的理解，真正重要的关键在于如何结合贝叶斯方法去拟合线性模型。
为了便于理解，首先，我们假设实验数据来自于一个正态分布，$Y_{i} \sim \mathcal{N}\left(\mu, \sigma\right)$，其中 $Y_{i}$ 为 $i$ 个观测数据点，$\mathcal{N}$ 为正态分布，$\mu$ 为数据分布的均值，$\sigma$ 为变异。在贝叶斯框架下，该数据分布等同于 $p(Y|\theta)$ 似然（参数 $\theta$ 包含均值 $\mu$ 和变异 $\sigma$），因此，只需额外得到先验与边际似然就可以推测出后验分布。其中，实验数据 $Y_{i}$ 已知，模型参数 $\theta$ 未知，贝叶斯推断的目的就在于推测模型参数值，即实验效应大小。当假设先验参数值 $p(\theta)$ 已知时（可以根据以往研究结果进行设定），此时似然也是已知的 $p(Y|\theta)$。由于边际似然 $p(Y)$ 只是一个标量，且只会对后验分布进行缩放，因此忽略边际似然的计算，可以根据贝叶斯公式推断得到参数后验分布 $p(\theta|Y)$。需要注意的，参数后验分布 $p(\theta|Y)$不同于先验参数分布 $p(\theta)$，后者在前者的基础上额外考虑了数据似然的作用。换句话说，不同于频率学派框架直接通过数据得到模型参数，贝叶斯框架通过实验数据更新先验参数的值得到模型的后验参数。此时，贝叶斯框架可以看作是频率学派的一种拓展与延申。
通过贝叶斯模型拟合线性回归模型的方式与上述过程类似。
首先，将回归模型 $Y_{i}=\beta_{0} + \beta_{\delta}X_{i} + \epsilon_{i}$ 转写为 $Y_{i} \sim \mathcal{N}\left(\beta_{0} + \beta_{\delta}X_{i}, \epsilon\right)$，此时模型参数 $\theta$ 包括 $\beta_{0}$、$\beta_{\delta}$ 和 $\epsilon$ 三个部分。$X_{i}$ 代表了实验条件，比如任务难度，其中简单任务 $X=0$，困难任务 $X=1$。可见，当任务为简单时，实验数据采样与均值为 $\beta_{0}$，变异为 $\epsilon$ 的正态分布，当任务为困难时，数据采样与均值为 $\beta_{0}+\beta_{\delta}$，变异为 $\epsilon$ 的正态分布。
因此，在已知两个实验条件下的实验数据，以及设定先验参数分布后，可以通过贝叶斯公式得到参数的后验分布。
根据同样的原理，将混合模型的公式带入贝叶斯框架中可以得到如下概率分布表达 @eq:eq6：
$$ 
\begin{aligned}
Y_{i,j,k} & \sim \mathcal{N}\left({\beta_{0,i,k}+\beta_{\delta,i,k} X_{i,k}, \epsilon_{i,j,k}}\right) \\
\beta_{0,i,k} &= \beta_{0} + \beta_{i,k} \\
\beta_{\delta,i,k} &= \beta_{\delta} + \gamma_{i,k}
\end{aligned} 
$$   {#eq:eq6}

此时的模型参数$\theta$包括 $\beta_{0}$、$\beta_{i,k}$、$\beta_{\delta}$、$\gamma_{i,k}$ 和 $\epsilon$ 五个个部分（如果考虑随机效应间的相关性还需设定其他参数，这里尽量简化模型方便理解）。

由于模型参数增加，贝叶斯在计算时会遇到困难，因此会采用mcmc采样，即brms中使用的算法。这种算法通过从后验分本中采集样本来模拟真实的后验分布。

