---
title: "数据模拟代码"
author: "Xiujuan Wen, Panwan Ke, Haiyang Jin"
date: '2022-07-25'
output:
  word_document:
    toc: yes
    toc_depth: '4'
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---
```{r setup, results='hide', include = FALSE}
#首先加载需要使用的R包
library("papaja")
if (!require(tidyverse)) {library(tidyverse)}
if (!require(faux)) {library(faux)}
if (!require(brms)) {library(brms)}
if (!require(bayesplot)) {library(bayesplot)}
if (!require(emmeans)) {library(emmeans)}
if (!require(tidybayes)) {library(tidybayes)}
if (!require(bayestestR)) {library(bayestestR)}
set.seed(2022)
```

在模拟实验中，40名抑郁症患者和40名健康对照组被试观看30张积极和30张中性图片，期间我们收集了他们的脑电数据。因变量是晚期正电位（late positive potentials, LPP）的波幅。简单来说，这是一个2 (组别`group`：抑郁症组`depression`、对照组 `control` ) × 2 (图片类型`type`：积极`positive`、中性`neutral`) 的混合实验设计，其中组别为被试间因素，图片类型为被试内因素。该假想实验的数据是使用DeBruine (2021)的faux工具包生成，下面是模拟这个实验所预设的参数。

```{r}
subj_n <- 80   # 总被试量：抑郁患者30人，健康对照组被试30人
trial_n <- 30  # 每张图片呈现的次数

# 固定效应
b0 <- 0.5       # 截距 (所有条件的均值)
b1 <- 6.5        # 图片类型的固定效应 (主效应)
b2 <- 0.1     # 组别的固定效应 (主效应)
b3 <- 0.1      # 图片类型与组别的交互作用

# 随机效应
u0s <- 2    # 被试的随机截距
u1s <- 2    # 被试的随机斜率 (图片类型)

# 误差项
sigma <- 2
```

之后根据假定的实验设计和参数来生成模拟数据：
```{r, results='hide'}
#生成假定实验的条件的数据矩阵
df_simu <- add_random(subj = subj_n) %>%
  # 添加被试的组别信息（被试间）
  add_between("subj", group = c("depression", "control")) %>%
  # 添加图片类型的信息（被试内）
  add_within("subj", type = c("netural","positive")) %>%
  # 每种图片呈现30次
  add_random(trial = trial_n) %>%
  # 图片类型的编码：中性=-0.5；正性=0.5
  add_contrast("type", "anova", colnames = "type_code") %>%
  # 被试组别的编码：抑郁症组=-0.5；控制组=0.5
  add_contrast("group", "anova",colnames = "group_code") %>% 
  # 添加基于被试的随机截距和斜率 (图片类型)
  add_ranef("subj", u0s = u0s, u1s = u1s, .cors=0.5) %>% 
  # 添加观察值的误差项
  add_ranef(sigma = sigma) %>% 
  # 最后根据设置的固定效应和随机效应参数值，生成因变量。
  mutate(LPP = (b0+u0s) +         # 截距
           (b1+u1s) * type_code + # 图片材料的斜率
           b2 * group_code +      # 组别的斜率
           b3 * type_code * group_code +   # 交互作用
           sigma)            #误差项
```


```{r results='hide'}
df_simu <- df_simu %>% 
  select(subj, group, type, LPP) # 去除冗余的信息
```


```{r}
#查看生成的数据
head(df_simu,10) 